# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20170614_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='request',
            new_name='prequest',
        ),
    ]
