# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20170614_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='program',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
    ]
